name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape magique : on convertit le nom du dépôt en minuscules et on le stocke dans une variable globale
      - name: Downcase repository name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      
      - name: Extract version from docker-compose
        run: |
          # Cherche "the-gatherer:" et récupère ce qui suit (la version)
          VERSION=$(grep -oP 'the-gatherer:\K[a-zA-Z0-9_.-]+' docker-compose.prod.yml | head -n 1)
          echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version trouvée : $VERSION"
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # On utilise la variable ${{ env.IMAGE_NAME }} qui est maintenant garantie en minuscules
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # LA DERNIÈRE ÉTAPE : On prévient Portainer que l'image est prête
      - name: Trigger Portainer Webhook
        run: curl -X POST "${{ secrets.PORTAINER_WEBHOOK }}"
